#!/usr/bin/python3
import pathlib
import sys


BRIDGE_DIRECTORY = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(BRIDGE_DIRECTORY))

from quick_chat.main import run  # noqa: E402


if __name__ == "__main__":
    run(sys.stdin, sys.stdout)
